### PR TITLE
Added More Function

### PR DESCRIPTION
**Pull request by ThisMe124**

### CODE REVIEW

**Comment by ThisMe124** [comment]
Nice

**Review by JastinXyz — COMMENTED** [review]
next update 🥶️🥶️

**Comment by JastinXyz** [comment]
added to [v3.0.6](https://npmjs.com/package/scramb/v/3.0.6). Belum ada di docs, masih nunggu approve dari js-org

**Comment by ThisMe124** [comment]
> added to [v3.0.6](https://npmjs.com/package/scramb/v/3.0.6). Belum ada di docs, masih nunggu approve dari js-org

Ok cuy

**Pull request merged**
